services:
  meshqtt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1883:1883" # MQTT port
      - "8883:8883" # MQTT TLS port
      - "8080:8080" # Management API port
      - "9000:9000" # Metrics port
    volumes:
      - ./config:/App/config:rw
      - ./logs:/App/logs:rw
      - ./certs:/App/certs:rw # TLS certificates directory

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    volumes:
      - ./logs:/logs:ro
      - ./fail2ban/jail.d:/data/jail.d:ro
      - ./fail2ban/filter.d:/data/filter.d:ro
      - ./fail2ban/action.d:/data/action.d:ro
      - ./fail2ban/fail2ban.local:/data/fail2ban.local:ro
    network_mode: "service:meshqtt"
    cap_add:
      - NET_ADMIN
      - NET_RAW
